### ISSUE TITLE
Add Foxy Releases of SwRI Repositories

### ISSUE THREAD

**Issue by danthony06** [ros2-gbp/marti_messages-release#1]
@nuclearsandwich, @daniel-dsouza and I are working on making Foxy releases of the following repos:

https://github.com/swri-robotics/marti_messages
https://github.com/swri-robotics/mapviz
https://github.com/swri-robotics/swri_console
https://github.com/swri-robotics/marti_common

marti_messages is already in ros2-gbp, but the others are still getting released out of our GitHub repos. We haven't done this before, and were hoping you could walk us through the process so we don't mess it up.

**Comment by nuclearsandwich** [comment]
> We haven't done this before, and were hoping you could walk us through the process so we don't mess it up.

Sure thing. I don't see existing ROS 2 release repositories for those projects and if that's the case then I can create new release repositories in ros2-gbp and grant your team access to them so they can be used from the outset. If there are release repositories I just didn't find we can either transfer them to the ros2-gbp organization or I can create new repositories and mirror what's in the current release repository before the next release.

**Comment by daniel-dsouza** [comment]
> I can create new release repositories in ros2-gbp

We would appreciate that. We currently do not have any ros2-specific (for foxy) release repositories for those repositories.

I've gone through the process of releasing a new package for ros1, however I'm not sure what the replacement for `catkin_generate_changelog` and `catkin_prepare_release` are in ros2.

**Comment by daniel-dsouza** [comment]
sorry to ping you again @nuclearsandwich, but have you had a chance to create the repositories yet? I was not able to find repositories for mapviz or swri_console searching through ros2-gbp.

**Comment by nuclearsandwich** [comment]
My apologies @daniel-dsouza I got in on the Dashing EOL work and this slipped off my TODO list.

I'm working on the import process right now and will have them ready to go shortly.

**Comment by nuclearsandwich** [comment]
@daniel-dsouza the repositories https://github.com/swri-robotics/gps_umd and https://github.com/swri-robotics/novatel_gps_driver also have ROS 2 releases. Would you like me to create ros2-gbp repositories for them as well?

**Comment by danthony06** [comment]
Yes, that would be great.

**Comment by nuclearsandwich** [comment]
Alright I've set up
* https://github.com/ros2-gbp/gps_umd-release
* https://github.com/ros2-gbp/marti_common-release
* https://github.com/ros2-gbp/mapviz-release
* https://github.com/ros2-gbp/novatel_gps_driver-release
* https://github.com/ros2-gbp/swri_console-release

with a complete set of refs from the previous gbp repositories and sent you invites to all of them. I'm hoping that we'll soon have new documentation together for making the management of release repositories and teams easier to request but you should be good to go in the meantime.

**Comment by nuclearsandwich** [comment]
@daniel-dsouza @danthony06 are we all good here?

**Comment by danthony06** [comment]
I think so, but we're probably going to wait until after the holiday weekend to work on it.

**Comment by nuclearsandwich** [comment]
@daniel-dsouza @danthony06 as mentioned in [this announcement](https://discourse.ros.org/t/upcoming-changes-to-ros2-gbp-organization/21878/4) we have reorganized permissions in the ros2-gbp organization. Both of you should have received invitations to join the organization and a team which has maintenance access to all of the above release repositories. In the coming days we will be retiring all outside collaborators.

**Comment by danthony06** [comment]
Been on travel, but I received the invitation.
